language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip
sudo: true
before_install:
  - sudo mkdir -m 777 -p /var/hdfs-mount
install: make
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
  - go: tip
