language: go
go:
  - 1.7
  - 1.6
  - 1.5
sudo: true
before_install:
  - sudo mkdir -m 777 -p /var/hdfs-mount
install: make
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
  - go: 1.5
